# Missão 1
apiVersion: v1
kind: Namespace
metadata:
  name: ufology

---
# Missão 4
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: ufology
data:
  DB_NAME: "ufology"
  REDIS_HOST: "redis-cache-service"
  DB_HOST: "ufodb-service"

---
apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: ufology
type: Opaque
stringData:
  DB_PASSWORD: "devops2025!"

---
# Missão 1
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ufodb-deployment
  namespace: ufology
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ufodb
  template:
    metadata:
      labels:
        app: ufodb
    spec:
      containers:
        - name: postgres
          image: leogloriainfnet/ufodb:latest
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: DB_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: DB_NAME
---
apiVersion: v1
kind: Service
metadata:
  name: ufodb-service
  namespace: ufology
spec:
  type: ClusterIP
  selector:
    app: ufodb
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432

---
# Missão 2
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-cache-deployment
  namespace: ufology
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-cache
  template:
    metadata:
      labels:
        app: redis-cache
    spec:
      containers:
        - name: redis
          image: redis:alpine
          ports:
            - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: redis-cache-service
  namespace: ufology
spec:
  type: ClusterIP
  selector:
    app: redis-cache
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379

---
# Missão 4
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ufotracker-app
  namespace: ufology
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ufotracker
  template:
    metadata:
      labels:
        app: ufotracker
    spec:
      containers:
        - name: ufotracker
          image: mendessz/ufotracker:v1
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://ufodb-service:5432/ufology"
            - name: POSTGRES_USERNAME
              value: "postgres"
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: DB_PASSWORD
            - name: SPRING_DATA_REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: REDIS_HOST
---
apiVersion: v1
kind: Service
metadata:
  name: ufotracker-service
  namespace: ufology
spec:
  type: ClusterIP
  selector:
    app: ufotracker
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080