name: Secret Demo
on: [push]
jobs:
  check-secret:
    runs-on: ubuntu-latest
    steps:
      - name: Check API Key
        env:
          MY_API_KEY: ${{ secrets.API_KEY }}
        run: |
          if [ -n "$MY_API_KEY" ]; then
            echo "API_KEY configurado"
          else
            echo "API_KEY não encontrado"
          fi